version: "3.3"

services:
  etl:
    container_name: etl_pipeline
    restart: always
    build:
      context: ./etl-pipeline/
      dockerfile: Dockerfile
    command: python3 main.py
    environment:
      - ETL_DB_CONTAINER_NAME=${ETL_DB_CONTAINER_NAME}
      - ETL_DB_PORT=${ETL_DB_PORT}
      - ETL_DB_NAME=${ETL_DB_NAME}

  db:
    container_name: $ETL_DB_CONTAINER_NAME
    restart: always
    image: mongo:latest
    volumes:
      - ${ETL_MONGO_DATA_DIR}:/data/db/